# DEV ENVIRONMENT

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

    ruleSelectorNilUsesHelmValues: false
    ruleSelector: {}
    ruleNamespaceSelector: {}

    # ðŸ‘‡ CORRECTED: Pointing to the specific Service Name found in your cluster
    alertingEndpoints:
      - namespace: monitoring
        name: monitoring-stack-kube-prom-alertmanager
        port: 9093
        pathPrefix: /

    retention: 2d
    resources:
      requests:
        memory: 256Mi

alertmanager:
  config:
    global:
      slack_api_url: "https://hooks.slack.com/services/PLACEHOLDER_TOKEN"