# DEV ENVIRONMENT

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

    ruleSelectorNilUsesHelmValues: false
    ruleSelector: {}
    ruleNamespaceSelector: {}

    # üëá RE-TARGETING: Point to the 'Old' Running Alertmanager
    alertingEndpoints:
      - namespace: monitoring
        name: monitoring-kube-prometheus-alertmanager # ‚ö†Ô∏è CHANGED: Pointing to the survivor
        port: 9093 # Try number first. If fails, we check name.
        pathPrefix: /

    retention: 2d
    resources:
      requests:
        memory: 256Mi

alertmanager:
  config:
    global:
      slack_api_url: "https://hooks.slack.com/services/PLACEHOLDER_TOKEN"