# PROD ENVIRONMENT
# Goal: High Availability, Data Safety.

prometheus:
  prometheusSpec:
    retention: 30d          # Keep data for 30 days (Audit)
    resources:
      requests:
        memory: 4Gi         # Big memory
    storageSpec:            # Persistent Volume (Don't lose data on restart)
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 50Gi

alertmanager:
  config:
    global:
      # Send alerts to the Real Channel + PagerDuty
      slack_api_url: "https://hooks.slack.com/.../prod-critical-alerts"